# Site
repository: hgup/hgup.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hursh Gupta
title: Student @ SSSIHL
email: hurgpt@gmail.com
#website: hgup.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: hurgpt
github_username:  hgup
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: hurgpt
#linkedin_username: hurgpt
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: hyperkey
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Medium Link
  icon: fab fa-medium
  url: https://hurshgupta.medium.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: |
  Hey, I am Hursh. I currently am having fun in life and hence, don't have much to talk about.

  **My Current Grindset**: <mark>Canva</mark> and <mark>Bullet Journaling</mark>

  **Updates** [20.04.22]: Preparing for <a href="https://www.soa.org/education/exam-req/edu-exam-fm-detail/">Exam FM</a>.

  **Recommend you to hear:** HalcyonMusic's <a href="https://www.youtube.com/watch?v=X6Z2sEfeoZk">Snow Halation</a> and <a href="https://www.youtube.com/watch?v=56j4TRL5yuQ">Higehiro OP</a>.



content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <a href="https://www.sssihl.edu.in">Sri Sathya Sai Institute of Higher Learning</a>
        caption: 2021 - Present
        sub_title: BSc Mathematics, Computer Science and Statistics
        quote: >
          Established in 1981, SSSIHL</a> is perhaps the most unique university in the world. Our need-based curricula, values-oriented teaching and associated public service component are our biggest strengths.
        description: |
          My time in SSSIHL has been wonderful. I am very lucky to be able to experience it in two different ways. The first being in the online medium, where I could only understand how to conduct myself and interact with my Professors.

          The second being, when I go there and live the campus life (which I highly await). I am highly inspired by all my Professors and of course The Master Himself.

      - layout: left
        title: <a href="https://www.ssshss.edu.in">Sri Sathya Sai Higher Secondary School</a>
        caption: 2019 - 2021
        sub_title: Mathematics, Physics, Chemistry and Computer Science
        quote: > 
          The Sri Sathya Sai Higher Secondary School was inspired and initiated by Bhagawan Sri Sathya Sai Baba Himself. He is its life and soul, motivation and goal.
        description: |
          This is where I was introduced to the __Ways of Sai__, this is where I learnt so many things about how to conduct myself.

          Not to mention, the amazing teachers and brothers that I was able to share my time here with. And also the countless number of activities that Swami had created for us.

          Everyday being as novel as the first. The drive and motivation that outlasts any other. This is how I would describe my time in SSSIHL.
         

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
